### ISSUE TITLE
加载引导到一半就卡住了，好像是在kext就卡住了

### ISSUE THREAD

**Issue by MichaelVector** [gunslinger23/XPS15-9560-High-Sierra#1]
大神你好，我也同样是XPS15-9560，i7-7700HQ，8G内存，128SSD+1T机械，装过10.12.6在机械上，现在想用你的clover引导重新安装OX10.13在自己机械的分区上，U盘引导一般就卡住了，不知道是不那个kext除了问题还是咋，安装界面都看不到，可以分享下你安装用的clover吗，不是已经装好的，我想全新安装，我想装10.13，多谢啦

**Comment by gunslinger23** [comment]
我已经把clover放在github啦(๑•̀ω•́๑)

**Comment by MichaelVector** [comment]
那我也是奇了怪了咱们配置那么像的，安装界面都进不去😭，我不是4K的，听说10.13是要afps驱动的是吗，和之前的10.12没啥不一样的吧😝

**Comment by gunslinger23** [comment]
是需要apfs驱动的。我提供的clover的drivers64UEFI里面的有，是从安装包app里面提取的

**Comment by MichaelVector** [comment]
![img_20171025_094459](https://user-images.githubusercontent.com/11750854/31982212-2590cc5a-b98a-11e7-9708-459c31cc0e19.jpg)
大神，一直不行啊，配置差不多，都用的你的clover就是到这里卡主不动了，最后面是啥text也没有写出来，好像图标都残了，问下你安装的时候的EFI就是这个吗?我现在安装界面都还看不到不知道是哪出问题了……😭

**Comment by jinoueki** [comment]
請問您的BIOS版本是?

**Comment by MichaelVector** [comment]
你好朋友，我的BIOS是1.5.0.最新的，应该没有问题吧，256GSSD(NVME)+1T的机械，EFI和苹果盘都在机械上面

**Comment by MichaelVector** [comment]
@gunslinger23 大神，能否出个教程或者详细些的资料呢，包括BIOS设置相关的，感觉近在眼前就是不知道哪里出了问题了😭，如果方便的话加我微信帮我看一下，我愿意20块做酬劳弄好10.13，真心感激，微信：18629350621，黑苹果困扰我快一个月了好痛苦，再次感谢！

**Comment by gunslinger23** [comment]
@MichaelVector 你有没有看我贴上去的教程？

**Comment by gunslinger23** [comment]
@MichaelVector 全新安装推荐使用U盘重新制作一个clover，利用U盘引导进入安装界面，同时也方便调试。

**Comment by MichaelVector** [comment]
@gunslinger23 那个英文的教程看不懂😝，大概看的国内的教程，安装包用的黑苹果乐园的带clover的10.13镜像，clover是4222，难道还是安装包的问题吗，你的10.13的安装包哪里下的啊，有链接吗

**Comment by gunslinger23** [comment]
搞黑苹果不看英文教程怎么解决新问题？要学会自己爬贴呀。。。clover下载地址：http://sourceforge.net/projects/cloverefiboot/ 我的安装包是从AppStore下载的

**Comment by gunslinger23** [comment]
试试把BrcmFirmwareData.kext和BrcmPatchRAM2.kext删掉

**Comment by MichaelVector** [comment]
还是卡在了那里了，删掉也不行，请问你的安装包U盘制作的是在Mac OS下制作的原版系统吗?用cloverU盘引导?

**Comment by MichaelVector** [comment]
![img_20171010_210811](https://user-images.githubusercontent.com/11750854/32044691-d20dce88-ba70-11e7-92b8-58e5d5e697cc.jpg)
还是到这里，我不知道是不是kext加载的问题，我试过吧所有kext删了都好像不行，最后就剩一个FAKEsmc其他都删了，也不行，也是到这里

**Comment by MichaelVector** [comment]
![img_20171026_165948](https://user-images.githubusercontent.com/11750854/32044823-38d61b8e-ba71-11e7-8af0-0251ef8c375d.jpg)
就是这样~😭着急的

**Comment by gunslinger23** [comment]
我给的英文教程上有教怎么制作启动u盘，然后把我的clover复制进去，使用我给的clover启动即可。

**Comment by MichaelVector** [comment]
大神，昨天我用mac制作了原装的10.13的镜像进行安装，用的你的clover，还是出问题，
![img_20171028_092418](https://user-images.githubusercontent.com/11750854/32130266-0ffe7e2e-bbc8-11e7-9471-d63980b068af.jpg)
出现AppleIntelLpssI2C这个问题，好像是触摸板这方面USB之类的吧，不知道哪里有问题，Kext我看都加载了，是不是plist里面需要改动下

**Comment by gunslinger23** [comment]
再试试把BrcmFirmwareData.kext和BrcmPatchRAM2.kext删掉

**Comment by hunanluyang** [comment]
我也遇到同样的问题，删除无效还是无法解决xps9560 4k 256ssd版本

**Comment by gunslinger23** [comment]
试试用新上传的config.plist

**Comment by hunanluyang** [comment]
好～我找找～谢谢你～

**Comment by jinoueki** [comment]
請教一下，新上傳的config.plist改了哪些部分？

**Comment by gunslinger23** [comment]
看commit

**Comment by jinoueki** [comment]
謝謝。我下載比對一下。

**Comment by hunanluyang** [comment]
还是卡那一页，还有这个版本的clover皮肤不见了。。。

**Comment by hunanluyang** [comment]
卡在appleintellpss

**Comment by gunslinger23** [comment]
@hunanluyang 你有按照我贴上的英文教程制作启动U盘么？

**Comment by hunanluyang** [comment]
可能是我的步骤出错了 明天再研究下 成后后我会在此回复～谢谢你～

**Comment by jinoueki** [comment]
出现AppleIntelLpssI2C这个问题，請加上「LPCSensors.kext」應該就可以了。關於USB的問題，可以試試clover/Devices/USB 選項中將FixOwnership 勾選，應該可以過關。進入MAC開機畫面

**Comment by MichaelVector** [comment]
@jinoueki 好像不是呢
![untitled](https://user-images.githubusercontent.com/11750854/32150249-4d0f8694-bd4b-11e7-99a2-c47c689b5acb.jpg)
这里面的senser好像都有呢，我在网上查了好多关于AppleIntelLpssI2C的问题，都没有个确切答案，不知道是不是config有些不一样引起的？还是SSDT之类的？

**Comment by MichaelVector** [comment]
@gunslinger23 @jinoueki @hunanluyang 
换了新上传的config还是卡在AppleIntelLpssI2C这里呢😭
你们什么情况呢，有啥办法吗

**Comment by MichaelVector** [comment]
![img_20171030_091431](https://user-images.githubusercontent.com/11750854/32150911-16f6eb1c-bd53-11e7-8611-9d6b617bbc31.jpg)
情况就是这样了😓

**Comment by jinoueki** [comment]
這位大大所分享的kext裏沒有LPCSensors.kext，您自己上網搜一下，我也是先前遇到同樣問題，加入就可以了。

**Comment by hunanluyang** [comment]
@jinoueki 谢谢我试试 有进展会留言告知

**Comment by jinoueki** [comment]
是另外加上「LPCSensors.kext」，不僅僅是原大大code中所含的「FakeSMC_LPCSensors.kext」也要喔！！

**Comment by hunanluyang** [comment]
@jinoueki LPCSensors.kext他的包里面有

**Comment by hunanluyang** [comment]
@jinoueki是说错了 LPCSensors.kext他的包里面没有

**Comment by jinoueki** [comment]
對啊，所以必須您自己去找找，google 一下應該就有了

**Comment by hunanluyang** [comment]
@jinoueki 可否通过云端共享下 网络上无法找到，感谢

**Comment by jinoueki** [comment]
https://github.com/wmchris/DellXPS15-9560-OSX/tree/master/KNNSpeed/CLOVER/kexts/Other

**Comment by hunanluyang** [comment]
@jinoueki 感谢～

**Comment by gunslinger23** [comment]
@MichaelVector 你确定你是用我的clover启动么？

**Comment by jinoueki** [comment]
gunslinger23大大，我是用您的clover+我所說的kext才能啟動的。感謝

**Comment by hunanluyang** [comment]
我已用楼主的方法重新把原版安装文件复制到u盘里面了，用的是MBR格式，再装clover到efi分区然后再用楼主的clover替换后进入-v安装依旧卡在那个地方，u盘无读取灯。LPCSensors.kext也添加了，依旧无用～@MichaelVector @gunslinger23

**Comment by hunanluyang** [comment]
BrcmFirmwareData.kext和BrcmPatchRAM2.kext删掉后问题依旧

**Comment by MichaelVector** [comment]
我一会重新传一个修改的config，我已经安装好了驱动都完美，一会传上去 @jinoueki @hunanluyang 
另外，感谢大神的9560的附件，让我简单的吃上了黑苹果~ @gunslinger23

**Comment by MichaelVector** [comment]
[config.plist.zip](https://github.com/gunslinger23/XPS15-9560-High-Sierra/files/1429503/config.plist.zip)

**Comment by MichaelVector** [comment]
其他都是大神的文件，修改了config

**Comment by hunanluyang** [comment]
再次感谢～

**Comment by gunslinger23** [comment]
@MichaelVector 能用就行，改了哪里？我看看能不能归纳一下！

**Comment by hunanluyang** [comment]
@MichaelVector 问一下你是用什么软件写的包？

**Comment by hunanluyang** [comment]
@MichaelVector现在卡在IOConsoleUsers，你要不上传你的完整clover吧，

**Comment by hunanluyang** [comment]
找到原因了，我的是4k屏要改配置文件，总之这个包是适合1080屏幕的。没毛病～

**Comment by jinoueki** [comment]
＠hunanluyang 有時間的話，也把您的解決方式與過程貢獻給其他有同樣問題的人。謝謝

**Comment by lry9798** [comment]
@jinoueki 有解决的话当然会~但是目前尝试的方法都无果。

**Comment by gomybed** [comment]
@hunanluyang 同4k屏，怎么改的配置呢？？/

**Comment by gomybed** [comment]
thank you, 4k配置也可以用了，显存也正常了，无痛升级到10.13.1

**Comment by hunanluyang** [comment]
@gomybed Bios我也改了，还是卡在ioconsoleusers这里了，楼主的回复有两个连接，我该下载哪一个呢？

**Comment by hunanluyang** [comment]
还有启动参数我还要勾选其他的吗～谢谢大家

**Comment by gomybed** [comment]
@hunanluyang 楼主revert 一次，所以下面那个链接是最新的，不过建议是整个clover都替换了，除了config.plist，其他也有更新

**Comment by hunanluyang** [comment]
@gomybed 同4k依旧卡io,你有勾选哪些选项吗～

**Comment by gomybed** [comment]
@hunanluyang  我全部按github主的来，包括加4k补丁，改smbios,rt variables等的值，我的启动正常，所以自然启动参数关了-v。我在github主这次更新前启动不了的时候也有卡io, 然后改了 ig-platform-id这个值0x19160000，就启动了。然后这次更新 把我显存31m，没有4k等问题一并解决了。

**Comment by hunanluyang** [comment]
@gomybed 谢谢解答～我把Mac系统删了所以没办法改 可以麻烦你把你的配置文件传给我吗～谢谢你～

**Comment by gunslinger23** [comment]
@hunanluyang 你按照readme上面一步一步安装，记得看我贴上去的国外教程（里面是最新的U盘安装方法）。readme上有4K用户需要多安装的kext名字，你百度一下找一个最新的扔进clover就可以了。

**Comment by MichaelVector** [comment]
好久没上来看了，我把mac安装到了附硬盘机械硬盘上果然是卡的不行啊，实在慢，我现在 发现有个问题啊，盒盖睡眠以后，再次唤醒了没有声音了是什么鬼？这个咋修复啊？大神知道嘛？换kext还是该参数呢？

**Comment by MichaelVector** [comment]
哦，对，还有个问题是，触控两个指头就不行了呢，不奢求完美黑苹果，起码能像Win10一样，两指那样嘛，我网上查了好像没什么办法，多指操作这个没办法实现了嘛？

**Comment by gunslinger23** [comment]
@MichaelVector 我的外放睡眠唤醒后没问题，只有耳机有问题。
