### ISSUE TITLE
请问从10.13.1升级到10.13.2要准备什么？

### ISSUE THREAD

**Issue by bsns** [gunslinger23/XPS15-9560-High-Sierra#10]
以前的小版本升级直接下载，双击安装即可。
但是这次升级小版本到10.13.2，升级，重启，选择安装更新，读条结束却自动重启。
并没有更新到10.13.2
是否是clover需要覆盖新版本或者其它问题？

**Comment by gunslinger23** [comment]
需要覆盖新版本，然后看readme更新系统注意事项

**Comment by VAllens** [comment]
@gunslinger23 能详细说一下吗？
我按照你的`readme.md`里的 **系统小版本更新** 这一节内容做。
1.备份`SSD`盘里的`EFI/clover/kext/Other`文件夹到U盘，然后删除原文件夹。
2.将你提供的`CLOVER/kext/Other`文件夹复制到`EFI/clover/kext/Other`文件夹。
3.使用`Apple Store`的系统更新，升级`10.13.1`到`10.13.2`。
4.升级后，启动到`Mac`系统界面。
5.删除位于`EFI/clover/kext`路径，你提供的`Other`文件夹。
6.从U盘还原`Other`文件夹到`EFI/clover/kext`路径下。
7.启动`Kext Utility`输入密码，重建缓存后，自动重启。
8.卡在黑屏白苹果`LOGO`界面后，系统起不来了。
9.强制重新启动笔记本，在`Clover`界面，增加**Boot Args`-v`** 进入啰嗦模式。
得到如下提示：
```
OsxAptioFix2Drv: Starting overrides for \System\Library\CoreServices\boot.efi
Using reioc block: no, hibernate wake: no
does printf work??
```

**PS: `10.3.1`黑苹果系统，是使用你的教程顺利完成安装，并且正常使用的。**
### 感谢大神的辛勤奉献。 ###

**Comment by holoto** [comment]
如果硬盘使用了 APFS ,记得从提取10.13.2的 APFS 驱动到 clover 目录
