### ISSUE TITLE
三、四手势触控板的kext似乎没有生效？

### ISSUE THREAD

**Issue by yedians** [gunslinger23/XPS15-9560-High-Sierra#12]
三、四手势触控板的驱动是VoodooPS2Controller.kext吧？貌似没有生效？

**Comment by gunslinger23** [comment]
支持是支持，但是需要自己设置才能使用。

**Comment by xiaotiantiantian** [comment]
我也遇到这个问题了，说一下自己的不完整解决办法：
如果用gunslinger项目中提供的这个voodooPS2Controller.kext驱动的话，三指上划，左右划都是支持的，但是在trackpad设置选项中是空白。如果用RehabMan提供那个voodooPS2驱动，并且按照他的说明安装的话，在trackpad里面能看到设置选项，可以调整移动速度，但是只支持单指点击，双指三指都不支持了。
如果之后再换回来gunsliger提供这个驱动，设置选项虽然又空白了，但是之前设置单指点击和滚动速度会被保存下来。三指上划显示各个桌面和窗口可用，但是三指左划右划切换桌面不支持了。

**Comment by MichaelVector** [comment]
是的，我也是这个问题，能看到设置离有，但最多只能双指，三指以上用不了

**Comment by xiaotiantiantian** [comment]
发现一个软件，BetterTouchTool，可以调整一些触控板设置，比如触控板指针移动速度等等
