### ISSUE TITLE
升级到10.13.2后，提示：does printf work??

### ISSUE THREAD

**Issue by VAllens** [gunslinger23/XPS15-9560-High-Sierra#13]
@gunslinger23 

大神，我按照你的`readme.md`里的 **系统小版本更新** 这一节内容做。

1. 备份`SSD`盘里的`EFI/clover/kext/Other`文件夹到U盘，然后删除原文件夹。
2. 将你提供的`CLOVER/kext/Other`文件夹复制到`EFI/clover/kext/Other`文件夹。
3. 使用`Apple Store`的系统更新，升级`10.13.1`到`10.13.2`。
4. 升级后，启动到`Mac`系统界面。
5. 删除位于`EFI/clover/kext`路径，你提供的`Other`文件夹。
6. 从U盘还原`Other`文件夹到`EFI/clover/kext`路径下。
7. 启动`Kext Utility`输入密码，重建缓存后，自动重启。
8. 卡在黑屏白苹果`LOGO`界面后，系统起不来了。
9. 强制重新启动笔记本，在`Clover`界面，**Boot Args**增加`-v`进入啰嗦模式。

得到如下提示：
```
OsxAptioFix2Drv: Starting overrides for \System\Library\CoreServices\boot.efi
Using reioc block: no, hibernate wake: no
does printf work??
```

**PS: `10.3.1`黑苹果系统，是使用你的教程顺利完成安装，驱动扔到`SLE`，并且正常使用的。**
### 感谢大神的辛勤奉献。 ###

**Comment by gunslinger23** [comment]
更新一下驱动，有些驱动需要更新。你直接把github上驱动的扔进sle就可以了。

**Comment by VAllens** [comment]
问题是现在进不去系统了，如何破？？

**Comment by gunslinger23** [comment]
用u盘启动进系统

**Comment by VAllens** [comment]
U盘是旧的Clover版本，没有识别出Mac系统盘

**Comment by VAllens** [comment]
以前还是`10.13.1`版本的时候，U盘可以识别`Mac`系统盘，并且引导进去。
现在升级到`10.13.2`后，识别不了。

**Comment by gunslinger23** [comment]
那就在win把github的扔进去u盘咯

**Comment by VAllens** [comment]
好的，感谢大神，我立马尝试，么么哒

**Comment by gunslinger23** [comment]
你是已经安装好了吧？

**Comment by VAllens** [comment]
对的，更新到10.13.2之后，进去系统，查看了系统版本是10.13.2.
然后还原之前备份的驱动，重建缓存，再重启就起不来了

**Comment by gunslinger23** [comment]
你的驱动放在那里？

**Comment by gunslinger23** [comment]
看看sle里面有没有原来的驱动，或者直接把github上的重新扔进去覆盖，重建缓存。然后记得把clover里面的驱动也换成新的

**Comment by VAllens** [comment]
放在`SLE`里面，大神，只有进入系统，才能扔进去覆盖啊

**Comment by gunslinger23** [comment]
用u盘启动不了？

**Comment by VAllens** [comment]
将U盘里的CLOVER用你的最新版本覆盖后，引导识别出Mac系统盘了，但进去依旧提示does printf work？？

**Comment by VAllens** [comment]
然后我按照这个帖子里的解决方案：[[Solution] "does printf work?" freeze with osxaptiov2](http://www.insanelymac.com/forum/topic/330598-solution-does-printf-work-freeze-with-osxaptiov2)
在`Boot Args`增加`side=0`也不行，依旧提示`does printf work？？`

**Comment by gunslinger23** [comment]
https://github.com/wmchris/DellXPS15-9550-OSX/blob/10.13/Additional/slide_calc.md
按着上面的教程计算出自己的side填上去就好了

**Comment by VAllens** [comment]
@gunslinger23 
| Start     | Pages  | Slide |
|-----------|--------|-------|
| 40C69000  | 1E08C  | 519   |
| 100000000 | 37F800 |       |
我用 **518 519 520** 都试过了，依旧提示这个错误

**Comment by VAllens** [comment]
## 问题解决 ##

#### 1.准备 ####
首先，把`10.13.2`需要用到的驱动，放到U盘的EFI分区的`post/clover`和`post/sle`下。
（**PS**：`没有这两个文件夹目录，可以自己手动创建，这两个目录取自Post-install/CLOVER-Kexts和Post-install/SLE-Kexts的缩小写`）

之所以分开放，是因为有些驱动放到`SLE`下会导致系统起不来，无法驱动，只能把这类驱动放在`EFI/Clover/Kexts/Other`下。所以把能安装到`System/Library/Extensions`下的驱动扔到`post/sle`下，不能安装到`System/Library/Extensions`下的，则扔到`post/clover`下，待用。
（**PS**：我是按照教程[https://github.com/gunslinger23/XPS15-9560-High-Sierra/blob/master/README.md](https://github.com/gunslinger23/XPS15-9560-High-Sierra/blob/master/README.md)的第二步第二种方式 **安装kext到SLE(推荐)** 这种方式来安装`Kexts`，如果你第二步第一种方式，可以不需要分开放，全部扔到`post/clover`下即可）

#### 2.进入恢复模式，启动终端。 ####
1.    列出所有分区的卷名称，如果你知道自己`Mac系统分区`和 **`U盘EFI分区`** 两个名称，可以跳过这一步。
`ls /Volumes`
    找到自己的`Mac系统分区`和 **`U盘EFI分区`** 两个名称，比如我的`Mac系统分区`叫 **`HsMacOs`** ，**`U盘EFI分区`** 叫 **`USB_EFI`**
2.    依次输入以下命令：
```
cp -rf /Volumes/USB_EFI/post/sle /Volumes/HsMacOs/System/Library/Extensions
rm -rf /Volumes/EFI/EFI/Clover/Kexts/Other/*
cp -rf /Volumes/USB_EFI/post/clover /Volumes/EFI/EFI/Clover/Kexts/Other
rm -f /Volumes/HsMacOs/System/Library/PrelinkedKernels/prelinkedkernel
rm -rf /Volumes/HsMacOs/System/Library/Caches/*
touch /Volumes/HsMacOs/System/Library/Extensions
kextcache -u /Volumes/HsMacOs
reboot
```
**以上命令的解释：**
```
1.拷贝post/sle文件夹下的所有文件到System/Library/Extensions文件夹下。
2.删除Mac系统下EFI分区的EFI/Clover/Kexts/Other文件夹下所有内容。
3.拷贝post/clover文件夹下的所有文件到Mac系统下EFI分区的EFI/Clover/Kexts/Other文件夹下。
4.删除Mac系统分区下的System/Library/PrelinkedKernels/prelinkedkernel文件。
5.删除Mac系统分区下的System/Library/Caches下的所有文件。
6.对Mac系统分区下的System/Library/Extensions文件夹重建权限。
7.对Mac系统分区重建缓存。
8.重启系统。
```

### PS： ###
我是参考[[Solution] "does printf work?" freeze with osxaptiov2](http://www.insanelymac.com/forum/topic/330598-solution-does-printf-work-freeze-with-osxaptiov2/)这个帖子才把问题解决的，但该帖子的[第10楼](http://www.insanelymac.com/forum/topic/330598-solution-does-printf-work-freeze-with-osxaptiov2/#entry2553095)里给出的命令列表中：
`sudo -s`命令无效或未定义。
`rm -R /Volumes/VOLUME/System/Library/Caches/com.apple.kext.caches`这个命令也是无效，找不到`com.apple.kext.caches`这个文件。直接用`rm -rf /Volumes/HsMacOs/System/Library/Caches/*`代替。
`touch /Volumes/VOLUME/System/Library/Extensions`这个命令可能会提示`System/Library/PrelinkedKernels/prelinkedkernel`这个文件被xxxxx，重新执行一次`rm -f /Volumes/VOLUME/System/Library/PrelinkedKernels/prelinkedkernel`后再重新执行`touch /Volumes/VOLUME/System/Library/Extensions`试试。
我出现`does printf work??`的根本原因是因为没有更新`SLE`下的自定义驱动。
所以只要有办法更新`SLE`下的自定义驱动，并且 **`重建权限和缓存`**，问题基本上就解决了。
然后找个最新版本的`Clover`扔到`EFI`下。
