### ISSUE TITLE
雷电3问题和升级，XPS15 9550 4k

### ISSUE THREAD

**Issue by WalkerPan** [gunslinger23/XPS15-9560-High-Sierra#15]
鄙人从darkhandz大神哪里来的，是9550的机器，并且受到远景的同学们的点拨成功10.13
但是貌似无法直接升级10.13.1和10.13.2，请问大大这个教程是否适合我升级到10.13.2？
另外一点，雷电3真的可用吗（因为我是视频制作想外接amd显卡）
谢谢大神！

**Comment by gunslinger23** [comment]
1. 你只需要更新一下Lilu.kext这个驱动。https://github.com/vit9696/Lilu
2. 雷电3可用，但是不支持热插拔。

**Comment by WalkerPan** [comment]
@gunslinger23 雷电3是否是走雷电还是仅为usb-c？

**Comment by gunslinger23** [comment]
雷电

**Comment by WalkerPan** [comment]
@gunslinger23 哇开心~~~谢谢噻
除了lilu之外需要更新clover吗？

**Comment by gunslinger23** [comment]
你喜欢，注意配置问题，有些参数在新版本改了
