### ISSUE TITLE
用了你的Clover 找不到我的SSD 固态

### ISSUE THREAD

**Issue by chenxz2016** [gunslinger23/XPS15-9560-High-Sierra#18]
用了你的Clover 能进安装界面，但是无法找到我的SSD。
我的SSD是 海力士PC3000 1T的。

**Comment by gunslinger23** [comment]
你去远景查查，你可能需要重新分区。

**Comment by chenxz2016** [comment]
已经解决了，谢谢！
另外你的Clover 好像没有解决电池的问题。我的电池还是显示为0.

**Comment by moruobing** [comment]
怎么解决的？我也遇到同样的问题，PC300无法识别，磁盘工具看不到固态硬盘，请大神告知，谢谢 @ @chenxz2016
