### ISSUE TITLE
试用了您的系统，有两个问题想咨询一下

### ISSUE THREAD

**Issue by moruobing** [gunslinger23/XPS15-9560-High-Sierra#19]
目前使用了几天了，效果很不错。有两个问题，屏幕亮度无法调节，插电源的时候有时候出现电脑重启，想问问是哪里没有设置好，还是安装的过程有问题，如果有时间，请帮忙回答一下，谢谢！

**Comment by gunslinger23** [comment]
你的电脑型号是和我的一样么？如果是请看清楚安装kext这一步，按着我的教程做是不会出现这些问题的。

**Comment by moruobing** [comment]
是的，我的也是9560的，7700的cpu，只不过我的硬盘是海力士的pc300。现在就是亮度调节不了，其他的声音，键盘灯，快捷键都可以用，就是屏幕亮度不行。另外就是接电源的时候，百分之三十概率出现重启，这两天我还发现hdmi接口百分之百重启，找了好多办法都解决不了

**Comment by moruobing** [comment]
我试过一个小太阳的软件，说能调节亮度，但是也一样不管用的

**Comment by gunslinger23** [comment]
这肯定是驱动问题，自己折腾吧。反正驱动都给你了，我自己和别人都没有这个问题。

**Comment by VAllens** [comment]
@moruobing 你的是4K屏幕吗？美版还是大陆版？
PS:美版有指纹识别，并且硬盘和大陆版不一样。
我的电脑配置和 @gunslinger23 大神的电脑配置一模一样，完美使用 @gunslinger23 大神提供的驱动和配置文件

**Comment by moruobing** [comment]
是4k的屏幕，美版的，硬盘确实不一样，是海力士的pc300，估计硬件有差别吧

**Comment by moruobing** [comment]
@VAllens 请问一下，你安装的是哪个版本的系统，13.3的么？你的安装包是哪里下载的？

**Comment by VAllens** [comment]
is v13.3, download mac 13.3 system dmg package in the PcBeta bbs.
