### ISSUE TITLE
你有睡醒无声的问题吗

### ISSUE THREAD

**Issue by RockJesus** [gunslinger23/XPS15-9560-High-Sierra#2]
https://github.com/vit9696/AppleALC/tree/master/Resources/ALC298
layoutid 11 是我的声卡文件，可否帮我看下我该怎么改才能使用cc和verbstub
现在问题是 1.用cc扬声器才出声
2.耳机用alcplugfix才出声
3.睡醒后都不出声，要再运行一次alcplugfix的install.sh，然后插拔耳机后都恢复正常

**Comment by gunslinger23** [comment]
我并没有睡眠唤醒无声的问题，但是使用耳机会出现破音。暂时不想折腾=-=

**Comment by gunslinger23** [comment]
你的是什么机型？我并不是很懂怎么修改kext。但是你可以试试度娘一下，找一下教程。我试过不完全睡眠唤醒后是不出声的，这个应该是alcplugfix的bug。但是完全睡眠后唤醒就没有事了。

**Comment by RockJesus** [comment]
我是alienware 17 ，硬件配置差不多，alc269，我的现在配合cc /ssdt /alcplugfix 已经可以睡醒出声了
问下你的雷电口可以热拔插吗，我的必须开机前连接才能用

**Comment by gunslinger23** [comment]
雷电热插拔目前来说貌似没办法解决。

**Comment by RockJesus** [comment]
好吧，可以来308469644群里有时间一起研究哈
