### ISSUE TITLE
睡眠之后网络延迟非常大（DW1830）

### ISSUE THREAD

**Issue by foxni** [gunslinger23/XPS15-9560-High-Sierra#20]
我也是换了DW1830，顺便加装了一根天线，开机正常使用网络一点问题都没有，但是如果睡眠以后就出现网络延迟非常大的问题（ping路由延迟非常高，还有丢包）。看网络上好像有不少人有类似的问题，通过关闭节能选项里的『唤醒以供WIFI网络访问』确实能够解决，但是还是不清楚这里的原理是什么？

**Comment by gunslinger23** [comment]
只要不是苹果原装的网卡都会这样，也不知道为啥。
