### ISSUE TITLE
问一下电量问题有办法吗，实时调节的？

### ISSUE THREAD

**Issue by MichaelVector** [gunslinger23/XPS15-9560-High-Sierra#21]
您好，我还是第一个提issue的人呢哈，用了你的教程我用了很长时间的黑苹果了，再次感谢！
我现在用的显示器把电脑盒盖当主机用的，平时都不动电脑，有两个问题提一下，看是否能解决
1、电量的图标不会动，如果是91%会一直显示91%不动，不知道这是不是驱动的问题把，我用的istats也是不动奇怪的很，要是能解决更好。
2、睡眠不正常，我现在是电脑不开盖一直当主机用，链接的显示器，点睡眠的话会自动重启，完全重启，休眠也是一样，只能再次启动进win然后睡眠可以，不知道是不是clover里的darkwake的问题还是啥，请问你的有这样的情况吗？

**Comment by MichaelVector** [comment]
![2018-04-05 00 42 01](https://user-images.githubusercontent.com/11750854/38321499-69c79a02-386a-11e8-94ad-c927b6456118.png)
![2018-04-05 00 41 38](https://user-images.githubusercontent.com/11750854/38321511-6e2e0aea-386a-11e8-9321-63c76195b0de.png)

**Comment by gunslinger23** [comment]
你系统是什么版本？

**Comment by MichaelVector** [comment]
系统现在目前是10.13.4最新的，但这个问题一直存在

**Comment by MichaelVector** [comment]
感觉应该是驱动的问题吧，kext或者是clover里面的设置问题，系统应该不会影响，请问你的都好着呢吗

**Comment by gunslinger23** [comment]
嗯，你有把全部驱动安装到sle么？

**Comment by MichaelVector** [comment]
没有的，我全部的驱动都是放在efi里面下面的other的kext。难道是因为这个吗？问下这两个地方有啥不一样？我是想放在efi这样更新系统只要变一下efi里的文件还可以引导不会影响系统的原生性，我怕放sle里面开不了机就麻烦了

**Comment by gunslinger23** [comment]
你就按着现在我git上的kext全部扔到系统里面去，这样是比注入的效果好很多

**Comment by MichaelVector** [comment]
哦哦这样啊，那我明天试试，多谢解答！早些休息！

**Comment by gunslinger23** [comment]
这也是我教程为啥推荐你这样做的原因。

**Comment by xxxzc** [comment]
放other里没影响的 发自谢子聪 在2018年04月05日 01:44，Gunslinger 写道： 你就按着现在我git上的kext全部扔到系统里面去，这样是比注入的效果好很多 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by MichaelVector** [comment]
明天我试试放sle看有啥变化没，即使更新，多谢楼上！

**Comment by gunslinger23** [comment]
你看commit，之前我就已经修复过电池的显示问题

**Comment by MichaelVector** [comment]
不好意思哈，有点看不懂你是咋修复的，更换KEXT吗，那个ACPImanager？

**Comment by gunslinger23** [comment]
启动项参数加上abm_firstpolldelay=16000

**Comment by MichaelVector** [comment]
多谢大神，电量的问题解决了，可以动态显示了，那请问睡眠的那个问题有办法吗？我是一睡就死，完了就自己重启了

**Comment by gunslinger23** [comment]
你把驱动扔进sle也不行么？

**Comment by MichaelVector** [comment]
是的，现在驱动全部都是在SLE里面，但还是没作用，和之前一样的

**Comment by gunslinger23** [comment]
5. Enable Intel SpeedShift (setup_var 0x4BC 0x1)
a. To enable Kaby Lake hardware P-states, which Dell has decided it wouldn’t add an option to do in the GUI (http://en.community.dell.com/support-forums/laptop/f/3518/t/20007733), requires a command-line setting. It's a setting just like any other, so resetting BIOS to default settings will clear this bit and it would then need to be reapplied.
b. Rockstar75 made a nice tutorial: http://forum.notebookreview.com/threads/dell-xps-speed-shift.796891/page-14#post-10454342
i. Don’t re-enable Secure Boot, obviously.​

你试试这个。需要篡改bios的，我的已经做了这步了。会有一定的风险

**Comment by MichaelVector** [comment]
![img_1539](https://user-images.githubusercontent.com/11750854/38409886-bfb3aa90-39b5-11e8-8316-c048437ef89c.jpg)
![img_1543](https://user-images.githubusercontent.com/11750854/38409889-c0014c46-39b5-11e8-8c74-f952fa1d2cf3.jpg)
![img_1540](https://user-images.githubusercontent.com/11750854/38409890-c0fd62c4-39b5-11e8-8c0d-8465bc28d659.jpg)
![img_1542](https://user-images.githubusercontent.com/11750854/38409892-c1638284-39b5-11e8-9699-fe32f118a8e0.jpg)
![img_1541](https://user-images.githubusercontent.com/11750854/38409893-c1d57d9e-39b5-11e8-8adb-c48babc0932a.jpg)
大神你看，我除了没有开虚拟加速以外，别的CPU性能全都在开着的，步进也打开了的

**Comment by MichaelVector** [comment]
嗯？speedshift不就是speedstep，动态调节CPU频率和电压的嘛，不过这个和休眠睡眠应该影响不大吧，我的电池动态调节已经弄好了，现在就是睡眠的问题，睡眠应该和这个没关系吧

**Comment by gunslinger23** [comment]
睡眠也应该是用到来调节的，睡眠电脑并非关机。内存CPU仍通电的。

**Comment by MichaelVector** [comment]
哦这么说我懂了，我BIOS里面打开了呀，步进，你给我的那个链接是调啥的，和BIOS里面那个设置不一样吗？

**Comment by gunslinger23** [comment]
不清楚，方法就这么多。你慢慢折腾？给你这个链接，我就是按着他的步骤弄的
https://www.tonymacx86.com/threads/guide-dell-xps-15-9560-4k-touch-1tb-ssd-32gb-ram-100-adobergb.224486

**Comment by foxni** [comment]
楼主说的SpeedShift跟BIOS里的SpeedStep不一样的，SpeedShift可以更快的变频，它是intel的一项新技术，虽然7代U里可以用，但是DELL已经明确说了在XPS15 9560这个先型号上不会加上BIOS开启选项。不过SpeedShift的开启其实并不是特别难，很多方法可以开启。不过我感觉，这个功能对睡眠未必有多大影响，建议你还是先捞一下日志看下睡眠以后的系统日志。

**Comment by MichaelVector** [comment]
多些@ foxni 给的答案，多谢作者大神这么帮忙，感觉很麻烦啊，暂时解决不了过段时间在看
