### ISSUE TITLE
请问从10.13.3升级到10.13.4要准备什么？

### ISSUE THREAD

**Issue by bahcer** [gunslinger23/XPS15-9560-High-Sierra#23]
知道主要更新了原生支持雷电3 外接显卡坞 但是说明文件里说更改了很多驱动的安装方式 不知道要做什么准备

**Comment by gunslinger23** [comment]
就把clover的驱动全部删掉，驱动全部装进sle而已

**Comment by BillTaozi** [comment]
![qq20180419-222753](https://user-images.githubusercontent.com/35515198/38997877-06ddab1c-4421-11e8-90c1-27319c4f6f34.png)
你确定要把四叶草里面的驱动全部删除后放在SLE吗？之前不是说蓝牙驱动不能放在SLE里面否则会导致无法启动吗?

**Comment by BillTaozi** [comment]
我现在是10.13.2，计划升级10.13.4，就怕出问题呢！

**Comment by gunslinger23** [comment]
是的，你要把现在新的驱动全部扔进去sle就能用了。蓝牙驱动已经解决了。

**Comment by gunslinger23** [comment]
请看最新的README

**Comment by BillTaozi** [comment]
好的，我试试，谢谢分享
