### ISSUE TITLE
似乎13.4的HDMI输出挂B了啊

### ISSUE THREAD

**Issue by jardenliu** [gunslinger23/XPS15-9560-High-Sierra#24]
刚刚试了一下插HDMI，并没有输出。应该是`com.apple.driver.AppleIntelKBLGraphicsFramebuffer`变了，patch没效果了

**Comment by MichaelVector** [comment]
不会的，我的KEXT都是原装的题主的KEXT，升级到10.13.4光升级了clover的核心文件，其他驱动都没动，现在显示还是好好的

**Comment by jardenliu** [comment]
你的是1080p？

**Comment by MichaelVector** [comment]
是的，1080P

**Comment by jardenliu** [comment]
试了一下SMBIOS设置成MacBookPro14,3，hdmi就挂B了，换成14,1或者14,2就没啥问题

**Comment by VAllens** [comment]
4k和1080p驱动有点不一样

**Comment by jardenliu** [comment]
@VAllens 你的SMBIOS设置成MacBookPro14,3能用hdmi？

**Comment by VAllens** [comment]
忘记了，很久没注意看。
我一般都是用这个仓库的默认配置即可。
我和仓库作者的一模一样

**Comment by gunslinger23** [comment]
不要改机型，跟我的保持一致就行

**Comment by jardenliu** [comment]
@gunslinger23 完全用你的clover就是不行，我(4K)和另一个也是4K屏的小伙子都有这个问题。SMBIOS 设置Macbook Pro14,3  就是丝毫没有输出

**Comment by VAllens** [comment]
姿势不对！！！ @jardenliu

**Comment by jardenliu** [comment]
@VAllens 能给个不要那么狗血的答案吗？

**Comment by VAllens** [comment]
BOIS版本多少？ @jardenliu

**Comment by VAllens** [comment]
之前我是1.5.0，现在是1.9.1.
你的BIOS版本太低了。

**Comment by jardenliu** [comment]
@VAllens 升级到1.9.1，还是一样然并卵

**Comment by VAllens** [comment]
从头装过...
PS:表示按照 @gunslinger23 大神提供的文件和教程，一步到位，非常顺利

**Comment by jardenliu** [comment]
微笑不说话

**Comment by foxni** [comment]
原因找到了。。。不要删除FakePCIID_Intel_HDMI_Audio.kext 和 NvidiaGraphicsFixup.kext 。

**Comment by jardenliu** [comment]
@foxni 问题解决了

**Comment by VAllens** [comment]
@jardenliu 你跟 @foxni  一样的问题吗？

**Comment by jardenliu** [comment]
@VAllens 问题一样，用它的办法解决了

**Comment by jardenliu** [comment]
打完安全补丁以后，HDMI又用不了

**Comment by jardenliu** [comment]
@foxni 之前我就在郁闷为什么要用到NvidiaGraphicsFixup.kext。然后我去看他的代码，虽然不是很懂，还是能看懂一些，哈哈哈！！发现里面有代码对AppleGraphicsDevicePolicy.kext进行patch。我去查了一下这个kext的作用，是一个显卡设备的代理，类似于管理HDMI这些输出口是使用独显还是集显。应该是更新了新的补丁，新的补丁里面更新了AppleGraphicsDevicePolicy.kext。NvidiaGraphicsFixup.kext对它的patch无效了。所以hdmi又挂逼了。

**Comment by jardenliu** [comment]
@foxni AppleGraphicsDevicePolicy.kext实在S/L/E下面的AppleGraphicsControl.kext的PlugIns里面。我替换了10.13.4的原版AppleGraphicsControl.kext到现在更新后的S/L/E里，然后重建缓存，重启，HDMI复活了。可惜我不会做KextsToPatch。

解决办法：替换10.13.4的原版AppleGraphicsControl.kext到现在更新后的S/L/E里，重建缓存，重启

**Comment by jardenliu** [comment]
@foxni 对比了一下，只是AppleGraphicsDevicePolicy.kext的版本号变了，其他都一样。加个`-ngfxbeta `的启动参数，应该也是可以的。

**Comment by foxni** [comment]
@jardenliu 我们只需要NvidiaGraphicsFixup.kext的一项patch，你可以试下这个KextToPatch，我的系统没有打安全补丁，测试没有问题。（记得删掉NvidiaGraphicsFixup.kext）
参考：https://github.com/lvs1974/NvidiaGraphicsFixup/blob/master/NvidiaGraphicsFixup/kern_ngfx.cpp#L178

> 
			<dict>
				<key>Comment</key>
				<string>Disable board-id check to prevent no signal ,thanks lvs1974, Pike R. Alpha, vit9696</string>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				ugUAAAA=
				</data>
				<key>MatchOS</key>
				<string>10.9.3,10.9.4,10.9.5,10.10.x,10.11.x,10.12.x,10.13.x</string>
				<key>Name</key>
				<string>com.apple.driver.AppleGraphicsDevicePolicy</string>
				<key>Replace</key>
				<data>
				ugAAAAA=
				</data>
			</dict>

**Comment by jardenliu** [comment]
@foxni 亲测，patch有效。感谢

**Comment by Leo428** [comment]
@jardenliu 大神你好，我想请问一下您具体是怎么操作的呢？怎样打这个patch？谢谢您的帮助！

**Comment by jardenliu** [comment]
我的github仓库config.plist已经打好

**Comment by Leo428** [comment]
@jardenliu 我刚才突然发现了，谢谢您！

**Comment by Leo428** [comment]
@jardenliu NvidiaGraphicsFixup.kext要从SLE里删除吗？

**Comment by jardenliu** [comment]
@Leo428 嗯

**Comment by Leo428** [comment]
@jardenliu 我现在接上HDMI可以显示连接到了。但是4k的显示器显示黑屏，换成2k的显示器就可以显示出来。这是什么原理。。。。

**Comment by jardenliu** [comment]
@Leo428 加了CoreDisplayFixup.kext？

**Comment by Leo428** [comment]
@jardenliu 对的。

**Comment by jardenliu** [comment]
@Leo428 不清楚，我测试了2K 1080P 4K的外接都没问题

**Comment by Leo428** [comment]
@jardenliu 谢谢您的帮助，我过两天有时间用您的仓库的文件重新好好装一次。

**Comment by jardenliu** [comment]
@Leo428 如果有用，麻烦点个star
