### ISSUE TITLE
想问下CPU变频和睡眠可以吗

### ISSUE THREAD

**Issue by Nikozhang996** [gunslinger23/XPS15-9560-High-Sierra#29]
你好，我是9560乞丐版用户，I5-7300HQ。你的变频有多少挡位呢？

**Comment by jardenliu** [comment]
@Nikozhang996 一样的，应该没啥问题

**Comment by MichaelVector** [comment]
@jardenliu @Nikozhang996 @gunslinger23 不知道你们用的都是什么档位，我有一个楼主额外 的变频档位，是800M，一般好像最低是i7-7700HQ的最低是1.3GHZ是吧， 最高时3.3还是3.2来着，我附加一个kext直接放在clover下就可以生效，或者安装到SLE下面，可以实现最低限制0.8GHz频率运行，很省电

**Comment by MichaelVector** [comment]
X86PlatformPluginInjector.kext
网不太好，传不上去，搜这个就可以了

**Comment by jardenliu** [comment]
@MichaelVector X86PlatformPluginInjector.kext，其实并不通用，和设置的SMBIOS也有关。
你想获得更好的电源管理，可以通过修改相对应配置来实现。

我用的是SMBIOS Macbook Pro 14,3 ，对应的`/System/Library/Extensions/IOPlatformPluginFamily.kext/Contents/PlugIns/X86PlatformPlugin.kext/Contents/Resources/Mac-551B86E5744E2388.pilst`。这个设置默认最低就是1.3GHZ。
可以修改里面的设置为800MHZ。然后用CPUFriend和CPUFriendProvider动态注入，然后就就能开启800了。X86PlatformPluginInjector.kext也是要修改的

**Comment by jardenliu** [comment]
两个远景的帖子有修改和注入的方法。
1、[开启完整HWP(SpeedShift)电源管理特性](http://bbs.pcbeta.com/viewthread-1737021-1-1.html)
2、[CPUFriend - 动态注入 CPU 电源管理数据](http://bbs.pcbeta.com/viewthread-1752935-1-1.html)

**Comment by jardenliu** [comment]
我的仓库也已经添加低频800MHz，https://github.com/jardenliu/XPS15-9560-High-Sierra

**Comment by VAllens** [comment]
@jardenliu 那么低频？纯办公用？我还希望能保持最高频，电不是事儿

**Comment by jardenliu** [comment]
@VAllens 。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

**Comment by jardenliu** [comment]
@VAllens 会自动变频的，不用的时候会在低频工作，比较省电

**Comment by VAllens** [comment]
只在不工作的时候低频运行？这个好

**Comment by jardenliu** [comment]
嗯
