### ISSUE TITLE
用ALC298PluginFix替代ComboJack，有兴趣的可以试一下

### ISSUE THREAD

**Issue by jardenliu** [gunslinger23/XPS15-9560-High-Sierra#30]
改了个ALCPlugFix的守护进程用来自动切换耳机插拔状态，有兴趣的小伙子可以到https://github.com/jardenliu/ALCPlugFix   看看。

我是先把ComboJack删了，再把我自己改的装上去的。

有问题可以到ALCPlugFix的issue留言，谢谢~

**Comment by jardenliu** [comment]
据说耳麦用不了，还没试。

**Comment by gunslinger23** [comment]
效果如何？

**Comment by VAllens** [comment]
效果如何？

**Comment by jardenliu** [comment]
@VAllens 优点是自动插拔切换咯，缺点是耳麦用不了，插了还是用的笔记本麦克风

**Comment by VAllens** [comment]
这个缺点有等于无，从不用耳麦和麦克风

**Comment by jardenliu** [comment]
之前combojack可以切换为耳麦模式，不知道是升级了系统还是bios，现在耳麦模式，麦克风还是走的电脑内建麦克风。和pluginfix效果基本一致。
