### ISSUE TITLE
有什么好的type-c网卡推荐吗

### ISSUE THREAD

**Issue by T-AI** [gunslinger23/XPS15-9560-High-Sierra#39]
之前是用戴尔的da200可以用但是后来坏了，我就买了个杂牌的结果用不了，各位有什么好的推荐吗？

**Comment by VAllens** [comment]
dell DA300 or WD15 or TB15

**Comment by T-AI** [comment]
DA300完美运行 谢谢

**Comment by 0xHJK** [comment]
> DA300完美运行 谢谢

你好，我的DA300插上无法使用，是需要安装什么驱动吗？
我的系统版本是10.14 (18A391)
