### ISSUE TITLE
USB启动MAC正常内置SSD启动MAC啰嗦模式最后显示三行MACH Reboot

### ISSUE THREAD

**Issue by VAllens** [gunslinger23/XPS15-9560-High-Sierra#4]
大神，USB启动MAC正常内置SSD启动MAC啰嗦模式最后显示三行MACH Reboot。
我的也是XPS 9560.
所有硬件配置几乎和你的一模一样，除了显示屏配置，你的应该是1080p的吧？我的是4K屏。

**Comment by gunslinger23** [comment]
硬盘的efi有没有放驱动？

**Comment by VAllens** [comment]
大神，我刚才度娘，有人说Clover Config注入Fix Header即可解决，但我搜索plist文件里确实有Fix Header。
后来在想是不是用Clover Configurator工具后，造成里面一些配置重置或丢失。
然后我直接把U盘那份配置文件直接扔到内置SSD的EFI里，可以正常启动。
我刚开始没有做plist文件比较，现在用beyond compare做新旧文件比较发现，你的(旧)文件里是FixHeaders_20000000，而经过Clover Configurator工具修改后的新文件变成了FixHeaders（PS：我仅仅修改了默认启动分区名称）。
现在我都不敢用Clover Configurator工具了，直接Sublime Text编辑。

**Comment by VAllens** [comment]
大神，这么晚还没睡觉阿？

**Comment by gunslinger23** [comment]
你的clover configurator太旧了，换个新的就好了

**Comment by VAllens** [comment]
我用的是`Clover Configurator 4.57 Vibrant` 最新版本哦？？26号凌晨才更新的。

**Comment by iGarym** [comment]
我也遇到这个问题了，用Clover Configurator之后就启动不了了。同样的FixHeaders_20000000变成FixHeaders，其它的变动应该都是正常的。等下回去试试手动改回去可不可以

**Comment by gunslinger23** [comment]
可能是clover新版变量名字改了。试试更新一下clover

**Comment by iGarym** [comment]
亲测，手动把 `FixHeaders` 改回来
 `FixHeaders_20000000` 就好了

**Comment by VAllens** [comment]
@gunslinger23 大神，我用的就是最新版`Clover`..
你能说下你的是`Clover`什么版本不？
我和 @iGarym 现在都是手动把`FixHeaders`改回`FixHeaders_20000000`.

**Comment by gunslinger23** [comment]
@VAllens 新版Configurator是针对新版的clover，你更新一下clover就好了。我用的是4.54
