### ISSUE TITLE
13.3升13.4 v图重启

### ISSUE THREAD

**Issue by VAllens** [gunslinger23/XPS15-9560-High-Sierra#40]
大神，按照你这个步骤升级后，重启到啰嗦模式界面滚动到有HAXM error错误的字样后，等一会就自动重启了，进不了系统
![image](https://user-images.githubusercontent.com/5094922/41598928-45398ac6-7404-11e8-9e2a-49b37e69084b.png)

**Comment by MichaelVector** [comment]
不留图怎么看？
