### ISSUE TITLE
升级10.13.5出的问题

### ISSUE THREAD

**Issue by MichaelVector** [gunslinger23/XPS15-9560-High-Sierra#42]
这样的两个图，不知道是不驱动的问题，上面说ACPI出错，acpi不是弄好以后硬件没变的情况下都不会有问题么，啥情况是
还有没次都会appleintellpssI2Ccontrol错误这个好像不影响直接会过去
![290380cc-7709-43f3-b183-b43ebea4720c](https://user-images.githubusercontent.com/11750854/41777386-b5f71c1e-765d-11e8-97e3-1baedc0597ae.jpeg)
![6b84cba9-57a3-4bb0-b34c-0b6cdb63bef4](https://user-images.githubusercontent.com/11750854/41777387-b66c2522-765d-11e8-952a-933f26cc36d1.jpeg)

**Comment by MichaelVector** [comment]
已解决，先把clover里kext里的Brcm两个驱动放到别的地方去，就可以进去安装了，安装完成了在原放回去蓝牙可以了

**Comment by VAllens** [comment]
你直接拍照的？？666
我记得可以让`Clover`记录啰嗦模式的日志。

**Comment by MichaelVector** [comment]
已经解决了，现在升级到了最新的10.14了，蓝牙不能用，睡眠不正常，其他都OK

**Comment by khaibin** [comment]
@MichaelVector 能够分享如何安装10.14吗？:D

**Comment by MichaelVector** [comment]
@khaibin 流程一样的哈，直接注册开发者安装描述文件，就可以在Apple Store升级下载最新的10.14，完了老样子安装就行
