### ISSUE TITLE
大神你好，我问个题外话

### ISSUE THREAD

**Issue by MichaelVector** [gunslinger23/XPS15-9560-High-Sierra#43]
最近在学习github，想问下你用的什么客户端和编辑器呢，我上传clover文件和文件夹好慢啊，有啥好的解决办法吗，已翻墙/
用的编辑器是Atom和github相关插件，传文件用的GithubDesktop桌面版传的文件。
问下你们都用的什么进行编辑和pull，push相关操作呢？
最近我也想出个教程，用Atom进行编辑和上传，碰到一些问题，求大神解答一下哈

**Comment by gunslinger23** [comment]
你用github提供的桌面版就够了，其他git客户端也可以，需要你自己折腾。Atom性能一般般，vscode了解一下？

**Comment by MichaelVector** [comment]
VScode我试过，新手哈，感觉不好看哈哈哈哈，莫怪啊，我是看Atom上面好多插件还可以同步插件感觉挺不错的，你说的性能指的是啥呢，打开文件的速度加载速度之类的吗还是？
现在黑苹果比较完美了，就主要在黑苹果下工作了，

**Comment by gunslinger23** [comment]
vscode也有很多插件

**Comment by MichaelVector** [comment]
哦哦，我用GitHub桌面版传文件，巨慢啊，你是咋传的，听说修改hosts？Mac也有啊？我自己翻墙用的ssr，

**Comment by gunslinger23** [comment]
不清楚，我这上传还是挺快的。现在我都不怎么用github了

**Comment by MichaelVector** [comment]
哦哦好的，多谢哈

**Comment by VAllens** [comment]
各`Git`桌面客户端，无论是`Github Desktop`还是`SourceTree`还是`TortoiseGit`性能都差不多，主要是受用户所在的网络影响。
`Mac`下，我首推`SourceTree`这个`Git+Hg`客户端，它功能很强大，**其中一个亮点就是支持文件部分内容提交，不像其它`Git`客户端只能提交整个文件**，更多亮点等待你去发现。
然后如果你在安装`SourceTree`的时候，首次运行，不想注册`Atlassian`账户的话，可以通过新建一个`accounts.json`文件绕过账户登录过程。
