### ISSUE TITLE
FireWolf OS X PE 9 with XPS 9560

### ISSUE THREAD

**Issue by VAllens** [gunslinger23/XPS15-9560-High-Sierra#44]
https://pe.firewolf.app/cn/
大神，有兴趣研究下这个`Mac PE`的`Clover with XPS 9560`适配吗？
方便我们在黑苹果系统起不来的时候，用`Mac PE`急救！
这个最近推出的最新`FireWolf OS X PE 9`基于`Mac OS X 10.13.x`版本制作。
**最重要的是支持`Mac`最新的文件系统格式`APFS`读写操作**

**Comment by gunslinger23** [comment]
直接用U盘clover引导启动这个PE就可以用了=-=

**Comment by VAllens** [comment]
最新的`SIP`要关闭，才能正常引导。
=^=

**Comment by VAllens** [comment]
而且按照老外的说法，这个镜像还有点问题。
得修改`com.apple.Boot.plist`文件。
https://telegra.ph/FireWolf-OS-X-PE-9-Troubleshoot-07-22

**Comment by vacarogit** [comment]
得修改com.apple.Boot.plist文件..無法改，磁碟是完全唯讀的

**Comment by VAllens** [comment]
@vacarogit 你可以燒錄磁碟到U盤后，再修改`com.apple.Boot.plist`文件，并且將`**Boot.FireWolf.OS.X.PE.9.ProPlus-Zlib.dmg**`重新命名為`**BaseSystem.dmg**`

**Comment by VAllens** [comment]
搞定
