### ISSUE TITLE
i5-8250U HD620显示花屏显存只有7MB

### ISSUE THREAD

**Issue by 0xHJK** [gunslinger23/XPS15-9560-High-Sierra#45]

**Comment by 0xHJK** [comment]
感觉提供的配置，按照这个配置可以成功安装并进入系统。
但是进入系统后显示会闪烁和花屏，关于本机那里显示只有7MB显存。
请问这个要怎么设置？
我的型号是XPS13 9360，i5-8250U

**Comment by gunslinger23** [comment]
显卡型号不一样呀，你需要找符合你机型的Clover配置文件

**Comment by 0xHJK** [comment]
> 显卡型号不一样呀，你需要找符合你机型的Clover配置文件

嗯嗯 我找到了 多谢啦
