### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by pp611** [gunslinger23/XPS15-9560-High-Sierra#5]
1. 请问您机器的BIOS是什么版本? 我的是1.50, USB安装盘boot有panic
2. 您机器是4K屏吗? 我的是4K屏, CLOVER boot的时候,遇到有 panic,字非常小, 看不清楚

**Comment by gunslinger23** [comment]
如果去启动不了试试我的clover，bios是1.5。其他问题你看看readme吧。我没4k不知道启动的时候是怎么样。

**Comment by pp611** [comment]
谢谢，拷贝了您的CLOVER目录以后，启动正常，安装成功。

我看您有NvidiaGraphicsFixup.kext，您的机器可以用NVDIA的卡吗？

我在这台机器上同时装了Win10，Ubuntu 和 OS X，我也安装了 Clover在 系统盘上，系统启动时只能看到Win和Ubuntu的启动项，没有进入Clover，按F12也没有Clover或OS X的选项。不知您有没有用Multiboot，有没有遇到同样的情况。

**Comment by gunslinger23** [comment]
N卡是用不了的，但不安装是会黑屏的。我的是win10+MacOS，你需要在BIOS里面自行设置添加启动项。文件指向CLOVER/CLOVERX64.efi。

**Comment by pp611** [comment]
謝謝，我也在BIOS裏試出了這個配置。再把CLOVER置成第一個bootloader，從CLOVER裏可以boot Win 和 Ubuntu

**Comment by pp611** [comment]
不過我的HDD上的CLOVER啓動系統是老會hang，安裝成CLOVER 4318就好了
