### ISSUE TITLE
使用了你的新驱动，无法启动

### ISSUE THREAD

**Issue by 914496397** [gunslinger23/XPS15-9560-High-Sierra#6]
安装在sle里面的，我还没找到是哪一个  ，正在重新安装。
使用的是你的clover和config

**Comment by gunslinger23** [comment]
重装直接用我的clover，扔进U盘即可。

**Comment by 914496397** [comment]
现在很奇怪的地步，我驱动放在clover里面是可以的，但是亮度无法调节，还要触摸板无法识别，但是丢在sle里面就开不了机（我重建缓存了）

**Comment by gunslinger23** [comment]
放在sle里的文件权限有没有检查？

**Comment by 914496397** [comment]
检查了，重复装了三次，安装到sle都有问题，我拷贝在clover没问题，（不过触摸板还是不行，不过我后来自己找的个最新的驱动，触摸板可以驱动，就是不支持多指）

**Comment by gunslinger23** [comment]
试试我新上传的触控板驱动

**Comment by 914496397** [comment]
可以使用，有两个bug  itunes闪退 触摸板空白

**Comment by gunslinger23** [comment]
试试更新一下itunes

**Comment by 914496397** [comment]
今天重装可以了，不过耳机是有噪音，并且声音小。基本上每期鱼问题了

**Comment by gunslinger23** [comment]
readme的第四步你做了么？那个能解决耳机问题。

**Comment by 914496397** [comment]
做了 但是好像没生效  但是是按照你的方法做的

**Comment by gunslinger23** [comment]
选择设备类型有没有选错？

**Comment by VAllens** [comment]
安装到`SLE`的话，万一更新驱动重建缓存后遇坑，想拯救都拯救不了，真悲催。

**Comment by neonlveyou** [comment]
触摸板空白怎么解决呀 还有不能三指拖拽了

**Comment by BillTaozi** [comment]
我的机子是Dell xps 15 9560 i7  7700HQ Mac10.13.1 我更新了触摸板驱动，但是没有什么反应？

**Comment by BillTaozi** [comment]
使用了你的新驱动，触摸板还是无法使用多手势功能，只能用简单的单指单击选择、双指单击打开右键、双指上下滑动网页，触控板可以设置，就是无法使用三指和四指，安装您的新驱动，升级无法进入系统，自动重起，更新kext驱动，触摸板三指和四指通用无法使用，而且您好像没有放显卡驱动，亮度无法调节；

**Comment by gunslinger23** [comment]
@BillTaozi 请看清楚教程一步一步装好驱动
