### ISSUE TITLE
谢谢作者

### ISSUE THREAD

**Issue by He-Xun** [gunslinger23/XPS15-9560-High-Sierra#8]
实测外接hdmi有效  我驳接了一个dell24寸的显示器 装好text之后 重启就好了 目前使用正常  
声音记得要切到本机  不然按音量键会没有效果  
最重要的是耳机的外放二合一解决了  简直是帮了我大忙

就是分区的时候 需要进终端敲 diskutil 工具的相关命令才能格式化成apfs的容器然后才能添加分区  自带的磁盘工具分区的时候会报错失败  幸亏我还学了一些linux 知识 才能hold住

whatever 非常感谢作者提供这么好的配置   3q

**Comment by gunslinger23** [comment]
其实安装的时候工具里有一个把分区转换为APFS分区，可以不用终端。还有感谢，开Issues是什么鬼233

**Comment by He-Xun** [comment]
哈哈 你就当成反馈贴  对了 
我在12.16的时候  触摸板是支持三指 四指操作的  是不是少了什么驱动  在设置里头点触摸板  什么也没有
